### ISSUE TITLE
Nice code ;)

### ISSUE THREAD

**Issue by torrentcome** [hebreuyannis/foodish#3]
Remember to take care of :

- Utils package is for Utils, be straight 
- in you're unit test, please follow the "good practice" of duckduckGo unit test naming (or another one but signal us the ref in the readme)

Else
- good understanding of Dagger, it's not so complex :)
- Well done man, that the way to doing stuff

**Comment by hebreuyannis** [comment]
Thank you for your advise ! 😁
I've create a new branch named update/create_test. Can you check out where i did a mistake because my last unit test failed
